services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: reportly
      POSTGRES_PASSWORD: "ssuHVcg6PpcOM8-KSFPsmEorsfqqjBWD"
    volumes:
      - reportly_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "dK8CGV7BJgS8AyPdysNmWDJKirX--QBb"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: reportly_test
      POSTGRES_PASSWORD: "7jNGIxyiAtjn4QPQOwgLLLVt3TO2k4-Q"
    volumes:
      - reportly_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "mwJQeaC7x8O2gx7sVbcCUniz_Q6yJ8Fm"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  reportly_data:
  reportly_test_data:
